# Generated by Django 3.2 on 2021-04-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_post_type_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='products',
            new_name='category',
        ),
    ]
